version: "3"
services:
  app:
    image: miguelpeixe/jitsi-provisioner
    command: ["nodemon", "server/index.js"]
    build: .
    ports:
      - 3030:3030
    volumes:
      - ${DATA_PATH}:/data
      - ./app:/app
    environment:
      - DEMO
      - MAX_INSTANCES
      - JWT_SECRET
      - EMAIL
      - DOMAIN
      - CLOUDFLARE_SECRET_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
