version: "3"
services:
  app:
    image: miguelpeixe/jitsi-provisioner
    build: .
    command: tail -f /dev/null
    volumes:
      - .data:/data
    environment:
      - EMAIL
      - DOMAIN
      - CLOUDFLARE_SECRET_KEY
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
