version: "3"
services:
  app:
    build: .
    command: ["nodemon", "server/index.js"]
    ports:
      - 3030:3030
      - 8888:8888
    volumes:
      - ${DATA_PATH}:/data
      - ./app:/app
    environment:
      - DEMO
      - MAX_INSTANCES
      - JWT_SECRET
      - EMAIL
      - DOMAIN
      - CLOUDFLARE_SECRET_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
