version: "3"
services:
  app:
    image: miguelpeixe/jitsi-provisioner
    restart: unless-stopped
    ports:
      - 80:3030
    volumes:
      - ${DATA_PATH}:/data
    environment:
      - NODE_ENV=production
      - DEMO
      - NO_CLIENT
      - MAX_INSTANCES
      - JWT_SECRET
      - EMAIL
      - DOMAIN
      - CLOUDFLARE_SECRET_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
